### PR TITLE
Support priority queue declarations

### PR DESCRIPTION
**Pull request by ebardes**
I'm working on project that benefits from using priority queues in RabbitMQ (available since version 3.5.x). I feel that others might benefit from this functionality too.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@ebardes you already can use priority queues with any client that supports optional queue arguments. While I couldn't quickly find an example of how to do that with this client in either examples or tests, I'd be really surprised if amqp.node didn't provide a way to do that.

**Comment by ebardes** [comment]
I couldn't find a way to declare a queue with the 'x-max-priority' flag. Perhaps I just missed it or that I'm not familiar enough with the nuances of amqp.node yet.

**Comment by michaelklishin** [comment]
Ah, so there's known argument filtering going on.

**Comment by ebardes** [comment]
Exactly. I just added another known argument.

**Comment by nikosd23** [comment]
This is very important for us! When do you plan to perform a new release with this included?

**Comment by michaelklishin** [comment]
@squaremo this PR looks good to me.

**Comment by nikosd23** [comment]
Tested with RabbitMQ 3.3.4 broker and it seems to create the queues successfully, ignoring the x-max-priority option making the change backwards compatible

**Comment by squaremo** [comment]
> Ah, so there's known argument filtering going on.

No there's not .. I see why you'd think that though. The second argument to `#assertQueue` is options, and an `x-*` argument would go in the _arguments_ table in the options:

    ch.assertQueue('prio', {arguments: {'x-max-priority': 10}});

whereas the "known options" go in the top level:

    ch.assertQueue('prio', {maxPriority: 10});

Anyway, yes this PR looks fine.

**Comment by michaelklishin** [comment]
@nikosd23 all unknown `arguments` will be ignored. They are all optional.

**Pull request merged**
