### PR TITLE
fix: travis ci script to use xenial VM

### PR DESCRIPTION
**Pull request by sshtel**
- use xenial VM image for travis CI.
- ~apt-get update before_install~
- ~npm run prepare to build before deploy~

since 0.5.5 is released, commit is updated

### CODE REVIEW

**Comment by sshtel** [comment]
image

To fix apt get install error, 

xenial VM is used

**Comment by squaremo** [comment]
I think the default is xenial, isn't it? That's why I had to redo a bit of the config, to install rabbitmq.

**Comment by sshtel** [comment]
Not sure if the default is xenial, I tried travis CI in my folk repo and failed multiple time until I implicitly define `dist`

if this is not needed, I will close.

**Comment by sshtel** [comment]
https://docs.travis-ci.com/user/reference/overview/

Trusty is default yet maybe?

**Comment by sshtel** [comment]
Since there is no issue for now, I will close this.

**Pull request closed without merging**
