### PR TITLE
Add overflow option to be set.

### PR DESCRIPTION
**Pull request by honestserpent**
Now when you declare a queue you can specify the overflow option (eg. "reject-publish"). ([documentation](https://www.rabbitmq.com/maxlength.html#overflow-behaviour))

Usage:
`await ch.assertQueue(q, { overflow: 'reject-publish' });`

### CODE REVIEW

**Comment by honestserpent** [comment]
What should I do? I don't understand why checks have failed.

**Comment by squaremo** [comment]
> I don't understand why checks have failed.

Me neither. Looks like a problem with npm. I've restarted the TravisCI build. If it keeps having problems, I'll have to do some investigation.

**Comment by honestserpent** [comment]
@squaremo After you restart. should I do anything?

**Comment by squaremo** [comment]
OK, one problem is with Node.JS 9.x, for small values of x, apparently: https://github.com/nodejs/node/issues/16781. I think I can just alter the version of Node.JS that's tested to a later one, to avoid it.

The other problem is genuinely in amqplib, just mysterious (and not your fault). It's a race in the muxing code that used to very rarely cause test flakes; now it seems to deterministically cause test flakes.

**Comment by squaremo** [comment]
OK, it may take me a while to fix those CI failures. If you remove the spurious whitespace changes, I'll merge this.

**Comment by honestserpent** [comment]
@squaremo pardon my ignorance but this is the first time I do a (very small) contribution on Github. Do i need to delete the Pull Request, fix it, and do it again, or is there some other way?

**Comment by honestserpent** [comment]
@kibertoad thank you.
@squaremo just done.

**Comment by squaremo** [comment]
> this is the first time I do a (very small) contribution on Github

@honestserpent Cool! 🎉

**Pull request merged**
